version: "3.8"
services:
  bffh:
    image: registry.gitlab.com/fabinfra/fabaccess/bffh:dev-latest 
    pull_policy: always
    restart: always
    ports:
      - "59661:59661"
    volumes:
      # generate a sample config.toml by running "docker run registry.gitlab.com/fabinfra/fabaccess/bffh:dev-latest --print-default > examples/config.toml" from the project root. You may have to delete the ipv6 listen section.
      - "./config:/etc/bffh"
    links:
      - mqtt
  mqtt:
    image: eclipse-mosquitto:1.6.13
